// <auto-generated />
namespace GestionPresence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Gestion_Presence : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gestion_Presence));
        
        string IMigrationMetadata.Id
        {
            get { return "202503180051430_Gestion_Presence"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
